package Server;

public class userCreation {
	public int create_user() {
		// INPUT USERNAME
		// CHECK USERNAME AVAILABLE
		// INPUT OTHER STUFF
		// CHECK IF SIN INPUT IS 9 LONG AND CONTAINS ONLY DIGITS
		// CHECK IF PASSWORD IS NOT NONE
		// CHECK INPUT FOR DATE -- IF THEY ARE >18 AND VALID DATE
		return -1;
	}
}
